[phases.setup]
nixPkgs = ["nodejs_20", "python311", "gcc", "gnumake"]
nixLibs = ["stdenv.cc.cc"]

[phases.install]
cmds = ["npm install --build-from-source"]

[phases.build]
cmds = ["npm run build", "npm run migrate"]

[start]
cmd = "npm start"

